-- MySQL Script generated by MySQL Workbench
-- dom 27 may 2018 17:07:16 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uparking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uparking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uparking` DEFAULT CHARACTER SET utf8 ;
USE `uparking` ;

-- -----------------------------------------------------
-- Table `uparking`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uparking`.`sede` (
  `idsede` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idsede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uparking`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uparking`.`zona` (
  `idzona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `disponibles carro` INT NOT NULL,
  `disponibles moto` INT NOT NULL,
  `idsede` INT NOT NULL,
  PRIMARY KEY (`idzona`),
  INDEX `fk_zona_sede_idx` (`idsede` ASC),
  CONSTRAINT `fk_zona_sede`
    FOREIGN KEY (`idsede`)
    REFERENCES `uparking`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
